var STOCK = {
    "spirits" :
        [{
            "nr": "1004703",
            "artikelid": "723841",
            "varnummer": "10047",
            "namn": "Nils Oscar Celebration Ale",
            "prisinklmoms": "43.70",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Sweden",
            "producent": "Nils Oscar Company",
	    "argang": "",
            "alkoholhalt": "9.4%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
            "stock": "30"
        },  {
            "nr": "156303",
            "artikelid": "34564",
            "varnummer": "1563",
            "namn": "Hoegaarden Wit-Blanche",
	    "prisinklmoms": "32.80",
            "varugrupp": "Beer",
	    "varutyp": "Wheat Beer",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Belgium",
            "producent": "InBev",
	    "argang": "",
            "alkoholhalt": "4.9%",
            "ekologisk": "0",
            "koscher": "1",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
            "stock": "35"
        } ,  {
            "nr": "1124601",
            "artikelid": "50229",
            "varnummer": "11246",
            "namn": "Scarecrow",
            "prisinklmoms": "14.90",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "33cl",
            "ursprunglandnamn": "Great Britain",
            "producent": "Wychwood Brewery",
	    "argang": "",
            "alkoholhalt": "4.7%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
            "stock": "33"
        }, 	 {
            "nr": "148503",
            "artikelid": "626980",
            "varnummer": "1485",
            "namn": "Hale to Nothing",
            "prisinklmoms": "34.90",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "Tap",
            "ursprunglandnamn": "Sweden",
            "producent": "Spendrups",
	    "argang": "",
            "alkoholhalt": "4.5%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
            "stock": "30"
        }
]};
