var DB2 = {
    "spirits" :
        [{
            "nr": "1004703",
            "artikelid": "723841",
            "varnummer": "10047",
            "namn": "Nils Oscar Celebration Ale",
            "prisinklmoms": "43.70",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Sweden",
            "producent": "Nils Oscar Company",
	    "argang": "",
            "alkoholhalt": "9.4%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "0",
	    "hidden": "1"
        },  {
            "nr": "156303",
            "artikelid": "34564",
            "varnummer": "1563",
            "namn": "Hoegaarden Wit-Blanche",
	    "prisinklmoms": "32.80",
            "varugrupp": "Beer",
	    "varutyp": "Wheat Beer",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Belgium",
            "producent": "InBev",
	    "argang": "",
            "alkoholhalt": "4.9%",
            "ekologisk": "0",
            "koscher": "1",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "5",
	    "hidden": "0"
        } ,  {
            "nr": "1124601",
            "artikelid": "50229",
            "varnummer": "11246",
            "namn": "Scarecrow",
            "prisinklmoms": "14.90",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "33cl",
            "ursprunglandnamn": "Great Britain",
            "producent": "Wychwood Brewery",
	    "argang": "",
            "alkoholhalt": "4.7%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "3",
	    "hidden": "0"
        }, 	 {
            "nr": "148503",
            "artikelid": "626980",
            "varnummer": "1485",
            "namn": "Hale to Nothing",
            "prisinklmoms": "34.90",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "Tap",
            "ursprunglandnamn": "Sweden",
            "producent": "Spendrups",
	    "argang": "",
            "alkoholhalt": "4.5%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "",
	    "hidden": "0"
        },  {
            "nr": "7155903",
            "artikelid": "200404",
            "varnummer": "71559",
            "namn": "Einbecker Dunkel",
            "prisinklmoms": "22.80",
            "varugrupp": "Beer",
	    "varutyp": "Lager",   
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Germany",
            "producent": "Einbecker Brauhaus",
	    "argang": "",
            "alkoholhalt": "4.9%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "8822303",
            "artikelid": "502145",
            "varnummer": "88223",
            "namn": "Sagres Bohemia",
            "prisinklmoms": "28.40",
            "varugrupp": "Beer",
	    "varutyp": "Lager",
	    "druva": "",
            "forpackning": "Tap",
            "ursprunglandnamn": "Portugal",
            "producent": "Central de Cervejas et Bebidas",
	    "argang": "",
            "alkoholhalt": "6.2%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "",
	    "hidden": "0"
        }, {
            "nr": "8916903",
            "artikelid": "650525",
            "varnummer": "89169",
            "namn": "Gold Star Dark Lager",
            "prisinklmoms": "38.90",
            "varugrupp": "Beer",
	    "varutyp": "Lager",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Israel",
            "producent": "Tembo Beer Industries",
	    "argang": "",
	    "alkoholhalt": "4.9%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "8839503",
            "artikelid": "794948",
            "varnummer": "88395",
            "namn": "Tommyknocker",
            "prisinklmoms": "26.20",
            "varugrupp": "Beer",
	    "varutyp": "Wheat Beer",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "USA",
            "producent": "Tommyknocker Brewery",
	    "argang": "",
	    "alkoholhalt": "4.7%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "1191103",
            "artikelid": "776557",
            "varnummer": "11911",
            "namn": "Lagunitas Maximus IPA",
            "prisinklmoms": "23.90",
            "varugrupp": "Beer",
	    "varutyp": "IPA",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "USA",
            "producent": "Lagunitas Brewing Company",
	    "argang": "",
	    "alkoholhalt": "8.2%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "1183203",
            "artikelid": "817610",
            "varnummer": "11832",
            "namn": "OkiDoki IPA",
            "prisinklmoms": "34.00",
            "varugrupp": "Beer",
	    "varutyp": "IPA",
	    "druva": "",
            "forpackning": "Tap",
            "ursprunglandnamn": "Netherlands",
            "producent": "All In Brewing",
	    "argang": "",
	    "alkoholhalt": "6.9%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "",
	    "hidden": "0"
        },  {
            "nr": "151301",
            "artikelid": "824201",
            "varnummer": "1513",
            "namn": "Twisted Thistle IPA",
            "prisinklmoms": "16.90",
            "varugrupp": "Beer",
	    "varutyp": "IPA",
	    "druva": "",
            "forpackning": "33cl",
            "ursprunglandnamn": "Scottland",
            "producent": "Belhaven Brewery",
	    "argang": "",
	    "alkoholhalt": "5.6%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        },{
            "nr": "8969603",
            "artikelid": "654371",
            "varnummer": "89696",
            "namn": "Piraten Pale Ale",
            "prisinklmoms": "23.30",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Sweden",
            "producent": "Lundabryggeriet",
	    "argang": "",
	    "alkoholhalt": "5.4%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "1",
	    "stock": "30",
	    "hidden": "0"
        },{
            "nr": "8844203",
            "artikelid": "848592",
            "varnummer": "88442",
            "namn": "Piratöl 5-1",
            "prisinklmoms": "15.20",
            "varugrupp": "Beer",
	    "varutyp": "Lager",
	    "druva": "",
            "forpackning": "33cl",
            "ursprunglandnamn": "Sweden",
            "producent": "Motala Brygghus AB",
	    "argang": "",
	    "alkoholhalt": "5.1%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "1",
	    "stock": "30",
	    "hidden": "0"
        },{
            "nr": "8221203",
            "artikelid": "835089",
            "varnummer": "82212",
            "namn": "Lucifer",
            "prisinklmoms": "37.60",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "Flaska 50cl",
            "ursprunglandnamn": "Belgium",
            "producent": "Brouwerij Het Anker",
	    "argang": "",
	    "alkoholhalt": "8%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "1",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "135603",
            "artikelid": "824225",
            "varnummer": "1356",
            "namn": "Old Speckled Hen",
            "prisinklmoms": "14.90",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "33cl",
            "ursprunglandnamn": "Great Britain",
	    "producent": "Old Speckled Egg AB",
	    "argang": "",
	    "alkoholhalt": "5%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "130403",
            "artikelid": "810995",
            "varnummer": "1304",
            "namn": "The Hoppy Bunny",
            "prisinklmoms": "19.90",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Sweden",
            "producent": "Train Station Brewery AB",
	    "argang": "",
	    "alkoholhalt": "4.5%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "1171503",
            "artikelid": "697169",
            "varnummer": "11715",
            "namn": "Old Fisherman\'s Ale",
            "prisinklmoms": "39.50",
            "varugrupp": "Beer",
	    "varutyp": "Ale",
	    "druva": "",
            "forpackning": "50cl",
            "ursprunglandnamn": "Belgium",
            "producent": "De Struise Brouwers",
	    "argang": "",
	    "alkoholhalt": "10%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "1",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "143103",
            "artikelid": "434852",
            "varnummer": "1431",
            "namn": "Sailor",
            "prisinklmoms": "30.90",
            "varugrupp": "Beer",
	    "varutyp": "Lager",
	    "druva": "",
            "forpackning": "Tap",
            "ursprunglandnamn": "Netherlands",
	    "argang": "",
	    "producent": "Three Towns Ind Brewers",
            "alkoholhalt": "5%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "0",
	    "innehall": "Gluten",
	    "special": "1",
	    "stock": "",
	    "hidden": "0"
        }, {
            "nr": "9949901",
            "artikelid": "868496",
            "varnummer": "99499",
            "namn": "Forster Pechstein",
            "prisinklmoms": "299.00",
            "varugrupp": "Wine",
	    "varutyp": "Dry White",
	    "druva": "Solaris",
            "forpackning": "Bottle",
            "ursprunglandnamn": "Germany",
            "producent": "Reichsrat von Buhl",
            "argang": "2012",
            "alkoholhalt": "13%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
         }, {
            "nr": "251701",
            "artikelid": "22520",
            "varnummer": "2517",
            "namn": "Yarden Chardonnay",
            "prisinklmoms": "136.00",
            "varugrupp": "Wine",
	    "varutyp": "Dry White",
	    "druva": "Prosecco",
            "forpackning": "Bottle",
            "ursprunglandnamn": "Israel",
	    "producent": "The Yarden Garden", 
            "argang": "2012",
            "alkoholhalt": "14%",
            "ekologisk": "0",
            "koscher": "1",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
	}, {
            "nr": "1224401",
            "artikelid": "14872",
            "varnummer": "12244",
            "namn": "Marie d\'Alsace",
            "prisinklmoms": "77.00",
            "varugrupp": "Wine",
	    "varutyp": "White",
	    "druva": "Solaris",
            "forpackning": "Bottle",
            "ursprunglandnamn": "France",
            "producent": "Jean Biecher",
            "argang": "2013",
            "alkoholhalt": "12%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "1",
	    "stock": "30",
	    "hidden": "0"
        },  {
            "nr": "9046201",
            "artikelid": "829858",
            "varnummer": "90462",
            "namn": "Le Mont Sec",
            "prisinklmoms": "75.00",
            "varugrupp": "Wine",
	    "varutyp": "Dry White",
	    "druva": "Muscat",
            "forpackning": "Glass",
            "ursprunglandnamn": "France",
            "producent": "Domaine Huet",
            "argang": "2011",
            "alkoholhalt": "13.5%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "9942602",
            "artikelid": "863064",
            "varnummer": "99426",
            "namn": "Masi Angelorum",
            "prisinklmoms": "149.00",
            "varugrupp": "Wine",
	    "varutyp": "Sweet Red",
	     "druva": "Dolcetto",
            "forpackning": "Bottle",
            "ursprunglandnamn": "Italy",
            "producent": "Masi",
            "argang": "2009",
            "alkoholhalt": "14%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        },  {
            "nr": "251801",
            "artikelid": "34443",
            "varnummer": "2518",
            "namn": "Hermon",
            "prisinklmoms": "116.00",
            "varugrupp": "Wine",
	    "varutyp": "Red",
	    "druva": "Kadarka",
            "forpackning": "Bottle",
            "ursprunglandnamn": "Israel",
            "producent": "Golan Heights Winery",
            "argang": "2012",
            "alkoholhalt": "14%",
            "ekologisk": "0",
            "koscher": "1",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
	}, {
            "nr": "1289008",
            "artikelid": "43331",
            "varnummer": "12890",
            "namn": "Cape Original Shiraz",
            "prisinklmoms": "70.00",
            "varugrupp": "Wine",
	    "varutyp": "Sweet Red",
	    "druva": "Corvina",
            "forpackning": "Glass",
            "ursprunglandnamn": "South Africa",
            "producent": "Origin Wine",
            "argang": "2014",
            "alkoholhalt": "13%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        },  {
            "nr": "8041901",
            "artikelid": "852818",
            "varnummer": "80419",
            "namn": "Organic Wine Zinfande",
            "prisinklmoms": "89.00",
            "varugrupp": "Wine",
	    "varutyp": "Red",
	    "druva": "Kadarka",
            "forpackning": "Bottle",
            "ursprunglandnamn": "Italy",
            "producent": "Icon Wines",
            "argang": "2013",
            "alkoholhalt": "13.5%",
            "ekologisk": "1",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "7905306",
            "artikelid": "802277",
            "varnummer": "79053",
            "namn": "Pruno",
            "prisinklmoms": "90.00",
            "varugrupp": "Wine",
	    "varutyp": "Red",
	    "druva": "graciano",
            "forpackning": "Glass",
            "ursprunglandnamn": "Spain",
            "producent": "Finca Villacreces",
            "argang": "2011",
            "alkoholhalt": "14%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "7695001",
            "artikelid": "841774",
            "varnummer": "76950",
            "namn": "Laurent Miquel",
            "prisinklmoms": "129.00",
            "varugrupp": "Wine",
	    "varutyp": "Rosé",
            "forpackning": "Bottle",
	    "druva": "Terrano",
            "ursprunglandnamn": "France",
            "producent": "Laurent Miquel",
            "argang": "2013",
            "alkoholhalt": "12.5%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "7650501",
            "artikelid": "852934",
            "varnummer": "76505",
            "namn": "Otazu Rosado",
            "prisinklmoms": "110.00",
            "varugrupp": "Wine",
	    "varutyp": "Rosé",
	    "druva": "Tannat",
            "forpackning": "Bottle",
            "ursprunglandnamn": "Spain",
            "producent": "Bodega del Selornado de Otazu",
            "argang": "2013",
            "alkoholhalt": "13.5%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Gluten Free",
	    "special": "0",
	    "stock": "30",
	    "hidden": "0"
        }, {
            "nr": "1",
            "artikelid": "1",
            "varnummer": "1",
            "namn": "Dry Martini",
            "prisinklmoms": "110.00",
            "varugrupp": "Cocktail",
	    "varutyp": "",
	    "druva": "",
            "forpackning": "Glass",
            "ursprunglandnamn": "",
            "producent": "",
            "argang": "",
            "alkoholhalt": "15%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Vermouth, Gin, Olives, Gluten Free",
	    "special": "0",
	    "stock": "",
	    "hidden": "0"
        }, {
            "nr": "2",
            "artikelid": "2",
            "varnummer": "2",
            "namn": "Mojito",
            "prisinklmoms": "70.00",
            "varugrupp": "Cocktail",
	    "varutyp": "",
	    "druva": "",
            "forpackning": "Glass",
            "ursprunglandnamn": "",
            "producent": "",
            "argang": "",
            "alkoholhalt": "10%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Lime, Mint, Sugar, Rum, Club Soda, Gluten Free",
	    "special": "0",
	    "stock": "",
	    "hidden": "0"
        }, {
            "nr": "3",
            "artikelid": "3",
            "varnummer": "3",
            "namn": "Cosmopolitan",
            "prisinklmoms": "130.00",
            "varugrupp": "Cocktail",
	    "varutyp": "",
	    "druva": "",
            "forpackning": "Glass",
            "ursprunglandnamn": "",
            "producent": "",
            "argang": "",
            "alkoholhalt": "17%",
            "ekologisk": "0",
            "koscher": "0",
	    "glutenfri": "1",
	    "innehall": "Vodka, Orange liqour, Cranberry Juice, Lime Juice, Gluten Free",
	    "special": "0",
	    "stock": "",
	    "hidden": "0"
        }
	]};
